---
  - name: Install the required packages
    yum: name={{ item }} state=present
    with_items:
      - libselinux-python
    tags: [ 'package', 'selinux_disable' ]

  - name: Disable SELinux
    selinux: state=disabled
    notify:
    - reboot
    - pause
    - wait
    tags: [ 'configuration', 'selinux_disable' ]
    
  - name: Flush handlers
    meta: flush_handlers
