---
- name: Install Nagios NRPE server
  yum: name=nrpe state=present
  tags: [ 'package', 'nrpe' ]

- name: Install Nagios NRPE plugins
  yum: name=nagios-plugins-all state=present
  notify: restart nrpe
  tags: [ 'package', 'nrpe' ]

- name: Create nrpe.cfg from template
  template: >
    src="nrpe.cfg.j2"
    dest="{{ nrpe_dir }}/nrpe.cfg"
    owner=root group=root mode=0644
  notify: restart nrpe
  tags: [ 'configuration', 'nrpe' ]

- name: Install global plugins
  copy: >
    src="{{ item }}"
    dest="{{ nrpe_plugins_dir }}/"
    owner=root group=root mode=0755
  with_fileglob:
  - plugins/*
  tags: [ 'configuration', 'nrpe' ]

- name: Ensure NRPE server is running
  service: name="{{ nrpe_service }}" state=started enabled=yes
  tags: [ 'service', 'nrpe' ]
