---
  - name: Disable iptables
    action: service name=iptables enabled=no state=stopped
    tags: [ 'configuration', 'iptables_disable' ]
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or
     (ansible_distribution == "RHEL" and ansible_distribution_major_version == "6")

  - name: Disable firewalld
    action: service name=firewalld enabled=no state=stopped
    tags: [ 'configuration', 'iptables_disable' ]
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7") or
      (ansible_distribution == "RHEL" and ansible_distribution_major_version == "7")
