---
- name: Install the required packages
  yum: name={{ item }} state=installed
  with_items: "{{ network_pkgs }}"
  tags: [ 'package', 'network' ]

- name: Write network configuration files for ethernet devices
  template: src=ethernet.j2 dest={{ net_path }}/ifcfg-{{ item.device }}
  with_items: "{{ ethernet_interfaces }}"
  when: ethernet_interfaces is defined
  register: ether_result
  tags: [ 'configuration', 'network' ]

- name: Write network configuration files for routes
  template: src=route.j2 dest={{ net_path }}/route-{{ item.device }}
  with_items: "{{ ethernet_interfaces }}"
  when: ethernet_interfaces is defined and item.route is defined
  tags: [ 'configuration', 'network' ]

- shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: "{{ ether_result.results }}"
  when: ether_result is defined and item.changed
  tags: [ 'service', 'network' ]
