---
- name: Cassandra | Download the Cassandra metrics jar
  get_url:
    url: "{{owm_tar_url}}/metrics-graphite-2.2.0.jar"
    dest: "{{cass_user[0].home}}/cassandra-blob/apache-cassandra-{{cassandra_source_version}}/lib/metrics-graphite-2.2.0.jar"
  tags: ['owm-cassblob', 'owm-cassblob-metrics']

- name: Cassandra | Update the cassandra metrics configuration
  template:
    src: "metrics-graphite-config.yaml.j2"
    dest: "{{cass_user[0].home}}/cassandra-blob/apache-cassandra-{{cassandra_source_version}}/conf/metrics-graphite-config.yaml"
    owner: "{{cass_user[0].username}}"
    group: "{{cass_user[0].username}}"
    mode: 0644
  tags: ['owm-cassblob', 'owm-cassblob-metrics']
