---
- name: Remove OpenJDK
  action: yum pkg=java-{{ jdk_openjdk_version }}-openjdk state=removed
  tags: [ 'package', 'jdk' ]

- name: Remove GCJ
  action: yum pkg=java-{{ jdk_gcj_version }}-gcj-compat state=removed
  tags: [ 'package', 'jdk' ]

- name: Install Oracle JDK
  action: yum pkg=jdk state=latest
  when: install_jdk_7_above is defined and install_jdk_7_above == "true" 
  tags: [ 'package', 'jdk' ]

- name: Update alternatives
  command: "{{ item }}"
  with_items:
  - /usr/sbin/alternatives --install /usr/bin/java java /usr/java/latest/bin/java 20000
  - /usr/sbin/alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 20000
  - /usr/sbin/alternatives --install /usr/bin/jar jar /usr/java/latest/bin/jar 20000
  tags: [ 'configuration', 'jdk' ]
