#!/bin/bash

#will clean everyting rexcept some config files nened.
host1=10.49.58.239
host2=10.49.58.240
host3=10.49.58.241


ssh root@$host1 "su - imail -c \"imboxdelete concuser@openwave.com\""
ssh root@$host1 "/etc/init.d/service-discovery stop"
ssh root@$host1 "ps -ef|grep "service-discovery"  |grep -v grep|awk '{print \$2}'|xargs kill -9"
ssh root@$host1 "ps -ef|grep -iw imail|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"
ssh root@$host1 "ps -ef|grep cass|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"
ssh root@$host1 "rm -rf /opt/imail/*"
ssh root@$host1 "rm -rf /opt/imail/.*"
ssh root@$host1 "rm -rf /opt/owm"
ssh root@$host1 "rm -rf /opt/owm/.*"
ssh root@$host1 "rm -rf /opt/cass/*"
ssh root@$host1 "rm -rf /opt/cass/.*"
ssh root@$host1 "ps -ef|grep cass|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"
ssh root@$host1 "rpm -qa|grep owm-|grep -v auto|xargs rpm -e"
ssh root@$host1 "rpm -qa|grep -i platformtools|grep -v auto|xargs rpm -e"
ssh root@$host1 "userdel -r imail"
ssh root@$host1 "userdel -r cass"
ssh root@$host1 "userdel -r owm"
ssh root@$host1 "groupdel  imail"
ssh root@$host1 "groupdel  cass"
ssh root@$host1 "groupdel  owm"
ssh root@$host1 "rm -rf /opt/merlin/*"
ssh root@$host1 "rm -rf /opt/merlin/.*"


ssh root@$host2 "/etc/init.d/search  stop"
ssh root@$host2 "ps -ef|grep -iw imail|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"
ssh root@$host2 "ps -ef|grep cass|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"
ssh root@$host2 "rm -rf /opt/imail/*"
ssh root@$host2 "rm -rf /opt/imail/.*" 
ssh root@$host2 "rm -rf /opt/owm/*"
ssh root@$host2 "rm -rf /opt/owm/.*"
ssh root@$host2 "rm -rf /opt/cass/*"
ssh root@$host2 "rm -rf /opt/cass/.*"
ssh root@$host2 "ps -ef|grep cass|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"
ssh root@$host2 "rpm -qa|grep owm-|grep -v auto|xargs rpm -e"
ssh root@$host2 "rpm -qa|grep sncr|grep -v auto|xargs rpm -e"
ssh root@$host2 "rpm -qa|grep -i platformtools|grep -v auto|xargs rpm -e"
ssh root@$host2 "userdel -r imail"
ssh root@$host2 "userdel -r cass"
ssh root@$host2 "userdel -r owm"
ssh root@$host2 "groupdel  imail"
ssh root@$host2 "groupdel  cass"
ssh root@$host2 "groupdel  owm"
ssh root@$host2 "rm -rf /opt/merlin/*"
ssh root@$host2 "rm -rf /opt/merlin/.*"


ssh root@$host3 "/etc/init.d/search  stop"
ssh root@$host3 "ps -ef|grep -iw imail|grep -v ssh|grep -v auto|awk '{print \$2}'|xargs kill -9"  
ssh root@$host3 "rm -rf /opt/imail/*"
ssh root@$host3 "rm -rf /opt/imail/.*"
ssh root@$host3 "rm -rf /opt/owm/*"
ssh root@$host3 "rm -rf /opt/owm/.*"
ssh root@$host3 "rpm -qa|grep owm-|grep -v auto|xargs rpm -e"
ssh root@$host3 "rpm -qa|grep sncr|grep -v auto|xargs rpm -e"
ssh root@$host3 "rpm -qa|grep -i platformtools|grep -v auto|xargs rpm -e"
ssh root@$host3 "userdel -r imail"
ssh root@$host3 "userdel -r cass"
ssh root@$host3 "userdel -r owm"
ssh root@$host3 "groupdel  imail"
ssh root@$host3 "groupdel  cass"
ssh root@$host3 "groupdel  owm"
ssh root@$host3 "rm -rf /opt/merlin/*"
ssh root@$host3 "rm -rf /opt/merlin/.*"

# remove packages under /root/
ssh root@$host1 "rm -rf sun-javadb*"
ssh root@$host1 "rm -rf apache-cassandra*gz" 
ssh root@$host1 "rm -rf jdk*rpm*" 
ssh root@$host2 "rm -rf sun-javadb*"
ssh root@$host2 "rm -rf apache-cassandra*gz" 
ssh root@$host2 "rm -rf jdk*rpm*" 
ssh root@$host3 "rm -rf sun-javadb*"
ssh root@$host3 "rm -rf apache-cassandra*gz" 
ssh root@$host3 "rm -rf jdk*rpm*" 

# remove service under systemd
ssh root@$host1 "rm -rf /etc/systemd/system/service-discovery.service" 
ssh root@$host1 "rm -rf /etc/systemd/system/cassmeta.service" 
ssh root@$host2 "rm -rf /etc/systemd/system/cassblob-cass.service"

#clean logs
ssh root@$host1 "rm -rf /var/log/sncr*" 
ssh root@$host1 "rm -rf /var/log/service-discovery" 
ssh root@$host1 "rm -rf /var/log/logstash" 
ssh root@$host1 "rm -rf /var/log/search*" 
ssh root@$host2 "rm -rf /var/log/sncr*" 
ssh root@$host2 "rm -rf /var/log/service-discovery" 
ssh root@$host2 "rm -rf /var/log/logstash" 
ssh root@$host2 "rm -rf /var/log/search*" 
ssh root@$host3 "rm -rf /var/log/sncr*" 
ssh root@$host3 "rm -rf /var/log/service-discovery" 
ssh root@$host3 "rm -rf /var/log/logstash" 
ssh root@$host3 "rm -rf /var/log/search*" 
