- name: Update the hostname (hostname command)
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags: [ 'configuration' , 'hostname' ]

- name: Update the hostname (/etc/hostname)
  copy:
    content: "{{ inventory_hostname_short }}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  when: "skip_hostnames is not defined"
  tags: [ 'configuration' , 'hostname' ]
