---
- name: Determine site name
  set_fact:
    node_site: "{{ item }}"
  with_items: "{{ sites }}"
  when: groups[item] is defined and inventory_hostname in groups[item]
  tags: [ 'owm-mss', 'owm-mss-init', 'mx' ]

- name: Check if owm-msg-common is installed
  command: rpm -q owm-msg-common
  register: rpm_check
  failed_when: rpm_check.rc > 1
  changed_when: no
  tags: [ 'owm-mss','mx' ]
  check_mode: no

- name: Checkf owm-msg-mss is installed 
  command: rpm -q owm-msg-mss
  register: rpm_check
  failed_when: rpm_check.rc > 1
  ignore_errors: True
  changed_when: no
  tags: [ 'owm-mss','mx' ]
  check_mode: no

- name: Fresh Install owm-msg-mss
  shell: 'INSTALL_USER={{emailmx_user[0].username}} INSTALL_GROUP={{emailmx_user[0].username}} GROUP_SITE={{node_site}} MSS_CLUSTER_NAME={{clusterId}} BLOBSTORE_CLUSTER_HOST={{blob_cluster_name}} BLOBSTORE_CLUSTER_PORT={{blobstore_cluster_port}} METADATA_CLUSTER_HOST={{meta_cluster_name}} METADATA_CLUSTER_PORT={{metadata_cluster_port}} rpm -ivh --prefix={{emailmx_user[0].home}} {{owm_repo_url}}/owm-msg-mss-{{emailmx_version}}.el6.x86_64.rpm'
  when: rpm_check.rc != 0
  tags: [ 'owm-mss','mx' ]

#
# Handle Upgrade / Downgrade
#

- name: Set Package Name
  set_fact: 
    package_name: "owm-msg-mss"
  tags: [ 'owm-mss','mx' ]

# Check specific version
- name: Get version of RPM
  shell: "`which yum` list installed {{ package_name }} | grep installed | awk '{ print $2 }'"
  register: rpm_version
  changed_when: False
  tags: [ 'owm-mss','mx' ]
  check_mode: no

- debug:
     msg: "System has {{ package_name }}-{{rpm_version.stdout}} installed"
  tags: [ 'owm-mss','mx' ]

# See which version is higher or lower
- name: Compare installed RPM version with expected version
  shell: '/tmp/compare_versions.sh {{emailmx_version}} {{rpm_version.stdout}}'
  register: version_comparison
  ignore_errors: yes
  when: rpm_check.rc == 0
  changed_when: False
  tags: [ 'owm-mss','mx' ]
  check_mode: no

- name: Print message when same version installed
  debug:
     msg: "Keeping the existing {{ package_name }}-{{rpm_version.stdout}} installed"
  when: rpm_check.rc == 0 and version_comparison.rc == 0
  tags: [ 'owm-mss','mx' ]

# Try to catch the case that user specified a RPM package that is not in the {{owm_repo_url}}
- name: Ensure {{owm_repo_url}} contains {{ package_name }}-{{emailmx_version}} RPM
  uri: 
    url: "{{owm_repo_url}}/{{ package_name }}-{{emailmx_version}}.el6.x86_64.rpm"
    method: HEAD
    status_code: 200
  register: rpmpkg_file
  when: rpm_check.rc == 0 and ( version_comparison.rc == 1 or version_comparison.rc == 2 )
  check_mode: no

- name: Print when package not found
  debug:
     msg: "{{ package_name }}-{{emailmx_version}}.el6.x86_64.rpm is not found in {{owm_repo_url}}"
  when: rpm_check.rc == 0 and ( version_comparison.rc == 1 or version_comparison.rc == 2 ) and rpmpkg_file.content_type != "application/x-rpm"
  check_mode: no

- name: Abort if the {{ package_name }}-{{emailmx_version}} RPM  is missing
  meta: end_play
  when: rpm_check.rc == 0 and ( version_comparison.rc == 1 or version_comparison.rc == 2 ) and rpmpkg_file.content_type != "application/x-rpm"
  check_mode: no

- name: User confirmation for upgrade
  debug: 
     msg: "Do you want to continue the {{ package_name }} upgrade from {{rpm_version.stdout}} to {{emailmx_version}} ?"
  when: rpm_check.rc == 0 and version_comparison.rc == 1 

- name: User confirmation for downgrade
  debug: 
     msg: "Do you want to continue the {{ package_name }} downgrade from {{rpm_version.stdout}} to {{emailmx_version}} ?"
  when: rpm_check.rc == 0 and version_comparison.rc == 2 

- pause: seconds=30
  when: rpm_check.rc == 0 and ( version_comparison.rc == 1 or version_comparison.rc == 2 )

- name: Stop MSS server
  command: runuser -l {{emailmx_user[0].username}} -g {{emailmx_user[0].username}} -c '{{emailmx_user[0].home}}/lib/imservctrl stop mss'
  when: rpm_check.rc == 0 and ( version_comparison.rc == 1 or version_comparison.rc == 2 )
  tags: [ 'owm-mss','mx' ]

# If application is already installed, and is a lower version do an upgrade
- name: Upgrade {{ package_name }} from {{rpm_version.stdout}} to {{emailmx_version}}
  shell: 'INSTALL_USER={{emailmx_user[0].username}} INSTALL_GROUP={{emailmx_user[0].username}} GROUP_SITE={{node_site}} MSS_CLUSTER_NAME={{clusterId}} BLOBSTORE_CLUSTER_HOST={{blob_cluster_name}} BLOBSTORE_CLUSTER_PORT={{blobstore_cluster_port}} METADATA_CLUSTER_HOST={{meta_cluster_name}} METADATA_CLUSTER_PORT={{metadata_cluster_port}} rpm -Uvh --prefix={{emailmx_user[0].home}} {{owm_repo_url}}/owm-msg-mss-{{emailmx_version}}.el6.x86_64.rpm'
  when: rpm_check.rc == 0 and version_comparison.rc == 1
  tags: [ 'owm-mss','mx' ]

# If application is already installed, and is a higher version, downgrade
# Downgrade Step #1 - remove old package
- name: Downgrade Step 1, remove old {{ package_name }}-{{rpm_version.stdout}} package
  shell: 'rpm -e {{ package_name }}-{{rpm_version.stdout}}'
  when: rpm_check.rc == 0 and version_comparison.rc == 2
  tags: [ 'owm-mss','mx' ]

# Downgrade Step #2 - install older package
- name: Downgrade Step 2, install older {{ package_name }}-{{emailmx_version}} package
  shell: 'INSTALL_USER={{emailmx_user[0].username}} INSTALL_GROUP={{emailmx_user[0].username}} GROUP_SITE={{node_site}} MSS_CLUSTER_NAME={{clusterId}} BLOBSTORE_CLUSTER_HOST={{blob_cluster_name}} BLOBSTORE_CLUSTER_PORT={{blobstore_cluster_port}} METADATA_CLUSTER_HOST={{meta_cluster_name}} METADATA_CLUSTER_PORT={{metadata_cluster_port}} rpm -ivh --prefix={{emailmx_user[0].home}} {{owm_repo_url}}/{{ package_name }}-{{emailmx_version}}.el6.x86_64.rpm'
  when: rpm_check.rc == 0 and version_comparison.rc == 2
  tags: [ 'owm-mss','mx' ]

# Check specific version
- name: Get new version of RPM
  shell: "`which yum` list installed {{ package_name }} | grep installed | awk '{ print $2 }'"
  register: rpm_version
  when: rpm_check.rc == 0
  changed_when: False
  tags: [ 'owm-mss','mx' ]
  check_mode: no

- name: Print when upgraded
  debug:
     msg: "System has {{ package_name }}-{{rpm_version.stdout}} installed (upgrade)"
  when: rpm_check.rc == 0 and version_comparison.rc == 1
  tags: [ 'owm-mss','mx' ]

- name: Print when downgraded
  debug:
     msg: "System has {{ package_name }}-{{rpm_version.stdout}} installed (downgrade)"
  when: rpm_check.rc == 0 and version_comparison.rc == 2
  tags: [ 'owm-mss','mx' ]

- name: Restart MSS server
  command: runuser -l {{emailmx_user[0].username}} -g {{emailmx_user[0].username}} -c '{{emailmx_user[0].home}}/lib/imservctrl start mss'
  when: rpm_check.rc == 0 and ( version_comparison.rc == 1 or version_comparison.rc == 2 )
  tags: [ 'owm-mss','mx' ]
  
- include: mss_maintenance.yml
  when: mx_maintenance
  tags: [ 'owm-mss','maintenance' ]
