---
- name: Configure PAM
  lineinfile: 
    create=yes dest=/etc/pam.d/common-session
    line="session required pam_limits.so"
  tags: ["configuration","limits"]

- name: Configure limits
  template: src=limits.conf.j2 dest=/etc/security/limits.d/{{limits_filename}}.conf
  tags: ["configuration","limits"]
