---
- hosts: confserv
  serial: 1
  roles:
    - owm-queue-search-configdb
    
- hosts: qsearch
  vars:
      initiate: 3
  serial: 1
  roles:
    - common
    - jdk
    - owm-common
    - owm-queue-search