---
- name: Create directory to store script files
  file: path={{cass_user[0].home}}/scripts state=directory mode=0755
  sudo: yes
  sudo_user: "{{cass_user[0].username}}"
  when: "inventory_hostname in groups['{{node_site}}-{{group_id}}']"
  tags: [ 'owm-cassmeta','maintenance' ]

- name: Cassandra maintenance script
  template:
    src: "cassmeta_maintenance.sh.j2"
    dest: "{{cass_user[0].home}}/scripts/cassmeta_maintenance.sh"
    owner: "{{cass_user[0].username}}"
    group: "{{cass_user[0].username}}"
    mode: 0644
  when: "inventory_hostname in groups['{{node_site}}-{{group_id}}']"
  tags: ['owm-cassmeta','maintenance']

- name: Create a cron job for repair,compact and cleanup 
  cron: name="Cron Job for Cassandra metadata maintenance" user="{{cass_user[0].username}}" minute="{{cassmeta_maintenance[0].minute}}" hour="{{cassmeta_maintenance[0].hour}}" day="{{cassmeta_maintenance[0].day}}" month="{{cassmeta_maintenance[0].month}}" weekday="{{cassmeta_maintenance[0].weekday}}" job="bash {{cass_user[0].home}}/scripts/cassmeta_maintenance.sh 2> /dev/null 2>&1"
  when: "inventory_hostname in groups['{{node_site}}-{{group_id}}']"
  tags: ['owm-cassmeta','maintenance']
