---

# Default host aliases
sudo_host_alias: {}

# Default user aliases
sudo_user_alias: {}

# Default command aliases
sudo_cmd_alias: {}

# Default sudo defaults
sudo_defaults:
  - requiretty
  - '!visiblepw'
  - always_set_home
  - env_reset
  - env_keep  = "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"
  - env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
  - env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
  - env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
  - env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"
  - secure_path = /sbin:/bin:/usr/sbin:/usr/bin

# Default sudo users
sudo_users:
  - root:
      host: ALL
      runas: ALL
      tag: ''
      cmd: ALL
  - '%wheel':
      host: ALL
      runas: ALL
      tag: ''
      cmd: ALL

# Default file includes
sudo_include: []

# Default directory includes
sudo_includedir:
  - /etc/sudoers.d
