---
epel_release:
  "4": 10
  "5": 4
  "6": 8
  "7": 5

epel_repo_url : https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm

epel_repo_gpg_key_location: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
