---
- name: Copy the /etc/yum.repos.d/CentOS-Base.repo template file
  template: src=CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo backup=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: [ 'configuration', 'yumrepo' ]

- name: Copy the /etc/yum.repos.d/CentOS-CR.repo template file
  template: src=CentOS-CR.repo.j2 dest=/etc/yum.repos.d/CentOS-CR.repo backup=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: [ 'configuration', 'yumrepo' ]

- name: Copy the /etc/yum.repos.d/CentOS-Debuginfo.repo template file
  template: src=CentOS-Debuginfo.repo.j2 dest=/etc/yum.repos.d/CentOS-Debuginfo.repo backup=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: [ 'configuration', 'yumrepo' ]

- name: Copy the /etc/yum.repos.d/CentOS-fasttrack.repo template file
  template: src=CentOS-fasttrack.repo.j2 dest=/etc/yum.repos.d/CentOS-fasttrack.repo backup=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: [ 'configuration', 'yumrepo' ]

- name: Copy the /etc/yum.repos.d/CentOS-Sources.repo template file
  template: src=CentOS-Sources.repo.j2 dest=/etc/yum.repos.d/CentOS-Sources.repo backup=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: [ 'configuration', 'yumrepo' ]

- name: Copy the /etc/yum.repos.d/CentOS-Vault.repo template file
  template: src=CentOS-Vault.repo.j2 dest=/etc/yum.repos.d/CentOS-Vault.repo backup=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tags: [ 'configuration', 'yumrepo' ]
