---
- name: Determine site name
  set_fact:
    node_site: "{{ item }}"
  with_items: "{{ sites }}"
  when: groups[item] is defined and inventory_hostname in groups[item]
  tags: [ 'configuration', 'hosts' ]

- name: Copy the /etc/hosts template file
  template: src=hosts.j2 dest=/etc/hosts backup=yes
  tags: [ 'configuration', 'hosts' ]

#- name: ecport "port_offset" in /etc/profile
#  lineinfile:
#    dest: '/etc/profile'
#    line: 'export PORTS_OFFSET={{PORTSOFFSET}}'
#  notify: reload_profile
#  tags: ['configuration', 'hosts']
