---
- name: Install the required packages
  yum: pkg={{ item }} state={{ ntp_pkg_state }}
  with_items: "{{ntp_pkgs}}"
  tags: [ 'package', 'ntp' ]

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp
  tags: [ 'configuration', 'ntp' ]

- name: Start/stop ntp service
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }} pattern='/ntpd'
  tags: [ 'service', 'ntp' ]
