---
- name: Verify Target is Primary Conf Server
  set_fact:
    proceed: true
  with_items: "{{groups['confserv']}}"
  when: "inventory_hostname == item and hostvars[inventory_hostname]['primary'] is defined"
  tags: [ 'owm-queue-search-configdb' ]

- name: Update ConfigDB for Queue Search Service
  template:
    src: "config-qsearch.sh.j2"
    dest: "/tmp/config-qsearch.sh"
    owner: "{{emailmx_user[0].username}}"
    group: "{{emailmx_user[0].username}}"
    mode: 0644
  when: "proceed is defined"
  tags: [ 'owm-queue-search-configdb' ]
  
- name: Run script config-qsearch.sh
  shell: "bash /tmp/config-qsearch.sh"
  when: "proceed is defined"
  tags: [ 'owm-queue-search-configdb' ]
  