---
- name: Verify Target is Primary Conf Server
  set_fact:
    proceed: true
  with_items: "{{groups['directory']}}"
  when: "inventory_hostname == item and hostvars[inventory_hostname]['primary'] is defined"
  tags: [ 'owm-mta-configdb', 'owm-mta-configdb-init' ]

- name: Copy mta-configdb.sh for stateless queue service
  template:
    src: "mta-configdb.sh.j2"
    dest: "/tmp/mta-configdb.sh"
    owner: "{{emailmx_user[0].username}}"
    group: "{{emailmx_user[0].username}}"
    mode: 0644
  when: "proceed is defined and use_stateless_queue is defined and use_stateless_queue == 'true'"
  tags: [ 'owm-mta-configdb' ]

- name: Run script mta-configdb.sh
  shell: "bash /tmp/mta-configdb.sh"
  when: "proceed is defined and use_stateless_queue is defined and use_stateless_queue == 'true'"
  tags: [ 'owm-mta-configdb', 'owm-mta-configdb-run' ]  