---
- name: Cassandra Service Unit
  template: 
    src: "cassblob.service.j2"
    dest: /etc/systemd/system/cassblob-{{ cass_user[0].username }}.service
    mode: 0644
  tags: [ 'owm-cassblob', 'systemd-unit' ]
    
- name: Reload Daemon
  shell: systemctl daemon-reload
  sudo: yes
  tags: [ 'owm-cassblob', 'systemd-unit' ]
    
- name: Startup Cassandra Blob
  service: name=cassblob-{{ cass_user[0].username }} state=started enabled=yes
  tags: [ 'owm-cassblob', 'owm-cassblob-startup' ]

