---
- name: Create directory for backup transfer keys for affinity
  file: path={{nginx_home_dir}}/backup_transfer_keys state=directory mode=0755
  sudo: yes
  sudo_user: "root"
  tags: [ 'owm-backup-setup','affinity' ]

- name: Copy rsa private key for affinity
  copy: src=~/.ssh/id_rsa dest={{nginx_home_dir}}/backup_transfer_keys/backup_transfer.rsa owner=root group=root mode=0600
  tags: [ 'owm-backup-setup','affinity' ]

- name: Copy rsa public key for affinity
  copy: src=~/.ssh/id_rsa.pub dest={{nginx_home_dir}}/backup_transfer_keys/backup_transfer.pub owner=root group=root mode=0600
  tags: [ 'owm-backup-setup','affinity' ]
