---
- name: Create directory for backup transfer keys for cassandra
  file: path={{cass_user[0].home}}/backup_transfer_keys state=directory mode=0755
  sudo: yes
  sudo_user: "{{cass_user[0].username}}"
  tags: [ 'owm-backup-setup','cassandra' ]

- name: Copy rsa private key for cassandra 
  copy: src=~/.ssh/id_rsa dest={{cass_user[0].home}}/backup_transfer_keys/backup_transfer.rsa owner={{cass_user[0].username}} group={{cass_user[0].username}} mode=0600
  tags: [ 'owm-backup-setup','cassandra' ]

- name: Copy rsa public key for cassandra
  copy: src=~/.ssh/id_rsa.pub dest={{cass_user[0].home}}/backup_transfer_keys/backup_transfer.pub owner={{cass_user[0].username}} group={{cass_user[0].username}} mode=0600
  tags: [ 'owm-backup-setup','cassandra' ] 
