---
    - name: reboot
      command: reboot
      
    - name: pause
      local_action: pause minutes=1 
      sudo: false
      
    - name: wait
      local_action: wait_for host={{ ansible_ssh_host }} state=started port={{ waitfor_port }}
      sudo: false 

