---
- name: Verify Target is Primary Conf Server
  set_fact:
    proceed: true
  with_items: "{{groups['directory']}}"
  when: "inventory_hostname == item and hostvars[inventory_hostname]['primary'] is defined"
  tags: [ 'owm-queue-admin-configdb' ]

- name: Update ConfigDB for Queue Admin Service
  template:
    src: "config-qadmin.sh.j2"
    dest: "/tmp/config-qadmin.sh"
    owner: "{{emailmx_user[0].username}}"
    group: "{{emailmx_user[0].username}}"
    mode: 0644
  when: "proceed is defined"
  tags: [ 'owm-queue-admin-configdb' ]
  
- name: Run script config-qadmin.sh
  shell: "bash /tmp/config-qadmin.sh"
  when: "proceed is defined"
  tags: [ 'owm-queue-admin-configdb' ]
  